### ISSUE TITLE
Triggering React actions from the clicks

### ISSUE THREAD

**Issue by dmk23** [alwinn1977/react-simple-flowchart#1]
I would like to make my React application respond to user's interaction with the flowchart

I see that the original library can support triggering of JavaScript by clicking on the flowchart nodes: https://github.com/adrai/flowchart.js/issues/100 , but it is not clear what might be the best way to connect raw JS (if the package is used "as is") with complied ES6 code of a React/Redux application

Any thoughts/ suggestions on implementing such integration?

**Comment by alwinn1977** [comment]
Hi! Update your component version to 1.2.1 and use onClick prop. See example for usage details.

**Comment by dmk23** [comment]
Thank you!
